### ISSUE TITLE
Is it possible add support for Cubism 5 AE Plugin?

### ISSUE THREAD

**Issue by Cloudstrifeff7** [ShigemoriHakura/rlm1221_Mod#1]
Is it possible add support for Cubism 5 AE Plugin? Thanks!

**Comment by ShigemoriHakura** [comment]
Nope, but you can check this post: [52](https://www.52pojie.cn/thread-1206572-1-1.html).
Just use ida you can easily hack the AE plugin.

**Comment by Cloudstrifeff7** [comment]
> Nope, but you can check this post: [52](https://www.52pojie.cn/thread-1206572-1-1.html). Just use ida you can easily hack the AE plugin.

Thank you very much for your answer! I had already found this post but I can't do it. Now I don't know if they changed something with version 5 or I misunderstood your instructions.

**Comment by ShigemoriHakura** [comment]
Nothing changed, search for license and you can find "License Error", find the xref and you can find the function, and modify the 00 to ff.
I patched one but haven't tried, send you by email?
![Patch](https://github.com/ShigemoriHakura/rlm1221_Mod/assets/62388797/4bdefbe5-66d8-4dd2-b44b-fcd9292dc3df)

**Comment by Cloudstrifeff7** [comment]
I have limited knowledge of IDA, so I'm not sure if I'm doing it correctly. Therefore, I will show you what I have done.

![ida1](https://github.com/ShigemoriHakura/rlm1221_Mod/assets/5221033/7db3b15a-eb84-4eb7-83f1-f99e5c2348e5)
![ida4](https://github.com/ShigemoriHakura/rlm1221_Mod/assets/5221033/b3527fd2-b3cc-443f-90f0-fbc09ebe0768)

I have followed these steps and I would like to ask if I have done everything correctly so far.

**Comment by Cloudstrifeff7** [comment]
Thanks!

![image](https://github.com/ShigemoriHakura/rlm1221_Mod/assets/5221033/f404b1b9-a067-4b82-ae8e-b013d86ed07a)

I double-clicked the mouse and I am here.

![image](https://github.com/ShigemoriHakura/rlm1221_Mod/assets/5221033/77f9a217-f45c-43c4-b20f-e2648e3dc510)

**Comment by ShigemoriHakura** [comment]
> Thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/5221033/341057131-f404b1b9-a067-4b82-ae8e-b013d86ed07a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTgxNDksIm5iZiI6MTcxODc5Nzg0OSwicGF0aCI6Ii81MjIxMDMzLzM0MTA1NzEzMS1mNDA0YjFiOS1hMDY3LTRiODItYWU4ZS1iMDEzZDg2ZWQwN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTE1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JjODExYjkwZjU3MDU4YmExYTg5ZGIxZDE3ZDRmZDNjOGYyNDEyNDQzZDZlZGIyMzVkNTYwNmZlMDdiZWRmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pVqnU27w5ouYAyd7cgPOz3FTXb_3XIEBu5aN4fthkQM)
> 
> I double-clicked the mouse and I am here.
> 
> ![image](https://private-user-images.githubusercontent.com/5221033/341057302-77f9a217-f45c-43c4-b20f-e2648e3dc510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTgxNDksIm5iZiI6MTcxODc5Nzg0OSwicGF0aCI6Ii81MjIxMDMzLzM0MTA1NzMwMi03N2Y5YTIxNy1mNDVjLTQzYzQtYjIwZi1lMjY0OGUzZGM1MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTE1MDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBhYmYxZDQwMDhjZTFjNWJjNDBkYTgzNzAyOWE3ZTEyYjhmMzc1OWNmNmRlYzJiZDY3ZGMwZDkzYzgyZTkxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RUxusIZ9ERDj_TN6JcehxdHgtymmTvbeSOTo1tpDKqA)

drag up

**Comment by Cloudstrifeff7** [comment]
![image](https://github.com/ShigemoriHakura/rlm1221_Mod/assets/5221033/2327a2b1-53e8-4759-8177-670c1a9a611f)

Now I have changed it to 0FFh.

I clicked save but it saved as database. How do I create a new file with this modification?

**Comment by ShigemoriHakura** [comment]
> ![image](https://private-user-images.githubusercontent.com/5221033/341064614-2327a2b1-53e8-4759-8177-670c1a9a611f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTkwMjgsIm5iZiI6MTcxODc5ODcyOCwicGF0aCI6Ii81MjIxMDMzLzM0MTA2NDYxNC0yMzI3YTJiMS01M2U4LTQ3NTktODE3Ny02NzBjMWE5YTYxMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTIwNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk5ZmE1NTgxZWUwNDJlMDU2MWY4MGY2MmQ0MjA5NzJjYjVlYjRhMmE0YWQwMjM5ZTJjNzVjYmY3MjkwNWZjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TRK1rr0JlsXAJu69CjKgmk0PYAkmUIf1DVczfcdejDw)
> 
> Now I have changed it to 0FFh.
> 
> I clicked save but it saved as database. How do I create a new file with this modification?

Edit->Patch program->Apply patches to...

**Comment by Cloudstrifeff7** [comment]
> > ![image](https://private-user-images.githubusercontent.com/5221033/341064614-2327a2b1-53e8-4759-8177-670c1a9a611f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTkwMjgsIm5iZiI6MTcxODc5ODcyOCwicGF0aCI6Ii81MjIxMDMzLzM0MTA2NDYxNC0yMzI3YTJiMS01M2U4LTQ3NTktODE3Ny02NzBjMWE5YTYxMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTIwNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk5ZmE1NTgxZWUwNDJlMDU2MWY4MGY2MmQ0MjA5NzJjYjVlYjRhMmE0YWQwMjM5ZTJjNzVjYmY3MjkwNWZjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TRK1rr0JlsXAJu69CjKgmk0PYAkmUIf1DVczfcdejDw)
> > Now I have changed it to 0FFh.
> > I clicked save but it saved as database. How do I create a new file with this modification?
> 
> Edit->Patch program->Apply patches to...

Thank you, ShigemoriHakura! Everything works perfectly! I also want to thank you for your patience in helping me.
